### PR TITLE
Setting up empty controllers, views and routes

### PR DESCRIPTION
**Pull request by ashleytqy**
- Set up all the basic views, routes and controllers
- No logic yet

### CODE REVIEW

**Review by laurachevalier4 — CHANGES_REQUESTED** [review]
Can you put all of the templates into a templates folder?

**Comment by danagilliann** [comment]
+1

**Comment by bettyybei** [comment]
I believe the templates are already in the templates folder (web/scalica/micro/templates/micro/)

**Review by bettyybei — APPROVED** [review]

**Comment by laurachevalier4** [comment]
@bettyybei you're right, I missed that

**Review by laurachevalier4 — APPROVED** [review]

**Pull request merged**
